services:
    mongodb:
        container_name: database
        image: mongo
        volumes:
        - mongodata:/data/db
    api:
        container_name: python_flask
        build: .
        ports:
        - "5000:5000"
        depends_on: 
        - mongodb

volumes:
    mongodata:
