services:
    api:
        container_name: python_flask
        build: .
        volumes:
        - ./:/palti_app
        working_dir: /palti_app/
        environment:
        - FLASK_APP=wsgi.py
        - FLASK_DEBUG=1
        command: flask run --host=0.0.0.0  #gunicorn --bind 0.0.0.0:5000 wsgi:app  #flask run --host=0.0.0.0
    
    webserver:
        container_name: http_server_reverse_proxy
        image: nginx:1.23-alpine
        ports:
        - 8888:80 
        environment:
        - NGINX_HOST=palti_app.com
        - NGINX_PORT=80
        volumes:
        - ./nginx/conf.d/:/etc/nginx/conf.d/

    mongodb:
        container_name: database
        image: mongo:4.2.23
        #restart: always
        environment:
        - MONGO_INITDB_USERNAME=usermongo
        - MONGO_INITDB_PASSWORD=userpwd
        - MONGO_INITDB_DATABASE=paltidb
        ports:
        - 27017:27017
        volumes:
        - ./mongodata/:/data/db

volumes:
    mongodata: {}
